parameters:
#    lm_commit.example.class: Lm\CommitBundle\Example

services:
#    lm_commit.example:
#        class: %lm_commit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
